### ISSUE TITLE
add picrust_test_data files

### ISSUE THREAD

**Issue by gregcaporaso** [picrust/picrust#97]
- [x] a_s_r.py     @mlangill (PR #105)
- [x] c_b_f.py     @mlangill (PR #116)
- [x] c_b.py       @mlangill (PR  #105)
- [ ] e_t_d.py     @zaneveld
- [x] f_t_a_t_t.py @mlangill (PR #105) 
- [ ] m_t_d.py     @zaneveld
- [x] m_c.py       @mlangill (PR #123)
- [x] n_b_c_n.py   @gregcaporaso (PR #99)
- [ ] p_t_d.py     @zaneveld
- [x] p_m.py       @gregcaporaso (PR #99)
- [x] p_t.py       @mlangill (PR #105)
- [ ] r_g_e.py     stall
- [ ] s_m.py       @zaneveld 
- [x] s_p_j.py     @gregcaporaso (PR #99)
- [x] s_p_j_s.py   @gregcaporaso (PR #99)
- [x] s_p_j_t.py   @gregcaporaso (PR #99)
